spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BENCHMARK?createDatabaseIfNotExist=true


  jpa:
    hibernate:
      ddl-auto: update # You can set this to "create", "update", "validate", etc., based on your needs.
    show-sql: true # Set to true if you want to see SQL statements in the console output.

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true # Enable Hibernate statistics to log SQL and other information
      javax:
        persistence:
          validation:
            mode: none # Set to "none" to disable Bean Validation

    open-in-view: false # Set to true if you want to enable the OpenEntityManagerInViewInterceptor

logging:
  level:
    org:
      hibernate:
        SQL: debug # Enable SQL logging
        type:
          descriptor:
            sql: trace # Log SQL parameter values
      springframework:
        data:
          jpa:
            show-sql: debug # Show SQL statements
  file:
    name: /home/ec2-user/benchmark_files/applicationlogfile.log # Update this with your desired log file path





manual-file-location: /home/ec2-user/benchmark_files/manual_files/
react-file-location: /home/ec2-user/benchmark_files/react_files/

file-upload-location: /home/ec2-user/benchmark_files/

protected-file-location: /home/ec2-user/benchmark_files/private_files/
public-file-location: /home/ec2-user/benchmark_files/public_files/