spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BENCHMARK?createDatabaseIfNotExist=true
    username: benchmark
    password: mySql!245

  jpa:
    hibernate:
      ddl-auto: update # You can set this to "create", "update", "validate", etc., based on your needs.
    show-sql: true # Set to true if you want to see SQL statements in the console output.

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            mode: none # Set to "none" to disable Bean Validation

    open-in-view: false # Set to true if you want to enable the OpenEntityManagerInViewInterceptor

file-upload-location: /home/master-x/testing_benchmark/

protected-file-location: /home/master-x/testing_benchmark/protected_files/
public-file-location: /home/master-x/testing_benchmark/public_files/
manual-file-location: /home/master-x/testing_benchmark/manual_files/